version: '2'
services:
  cerebro:
    tty: true
    image: lmenezes/cerebro:${image_version}
    entrypoint:
      - sh
      - -c
    command: 'echo "play.ws.ssl.loose.acceptAnyCertificate = true" >> /opt/cerebro/conf/reference.conf && /opt/cerebro/bin/cerebro'
    ${mem_limit}
    cpu_shares: ${cpu_shares}
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$$$${stack_name}/$$$${service_name}
      io.rancher.scheduler.affinity:host_label: ${label_scheduling}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: ${global_scheduling}